const $=id=>document.getElementById(id);let data,connected=false,editing=false,key='',fitTimer;
const labels={online:'Online',offline:'Offline',error:'Ping error',checking:'Checking',unknown:'Unknown',empty:'Not configured'};
const element=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
async function api(path,body){const r=await fetch('/api/'+path,{signal:AbortSignal.timeout(5000),...(body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Device-Monitor':'1'},body:JSON.stringify(body)})});const result=await r.json();if(!r.ok)throw Error(result.error||'Request failed');return result;}
function fit(){clearTimeout(fitTimer);fitTimer=setTimeout(async()=>{try{await api('fit',{settings:editing,width:innerWidth,height:innerHeight,content:Math.ceil(document.body.getBoundingClientRect().height)+2});}catch{}},350);}
function render(){if(editing)return;document.body.className=data?.view.size||'compact';document.documentElement.style.setProperty('--cols',Math.min(data?.view.columns||1,Math.max(1,data?.devices.length||0)));$('devices').replaceChildren();let online=0;for(const d of data?.devices||[]){let status=!connected||(d.checkedAt&&Date.now()-Date.parse(d.checkedAt)>25000)?'unknown':d.status;if(status==='online')online++;const row=element('article'),left=element('div',undefined,'left'),right=element('div',undefined,'right');left.append(element('div',d.name||'Unnamed','name'),element('div',d.ip||'','ip'));right.append(element('div',labels[status]||'Unknown','badge '+status));right.append(element('div',status==='online'?(d.latencyMs===0?'<1 ms':d.latencyMs+' ms'):status==='offline'?'No reply':'','detail'));const time=element('time',d.checkedAt?new Date(d.checkedAt).toLocaleTimeString([],{hour12:false}):'');time.title='Last ping';right.append(time);row.append(left,right);$('devices').append(row);}if(!data?.devices.length)$('devices').append(element('div','No devices','empty'));$('summary').textContent=connected?online+'/'+data.devices.filter(d=>d.ip).length:'Offline';const next=JSON.stringify([data?.view,data?.devices.map(d=>d.name)]);if(next!==key){key=next;fit();}}
async function poll(){try{data=await api('status');connected=true;if(data.app!=='disguise-device-monitor-v2')throw Error('Wrong helper version');}catch{connected=false;}render();setTimeout(poll,1000);}
function field(d={name:'',ip:''}){const row=element('div',undefined,'field');for(const [key,title]of [['name','Name'],['ip','IPv4 address']]){const label=element('label',title),input=element('input');input.value=d[key];input.dataset.key=key;input.maxLength=key==='name'?60:15;input.autocomplete='off';label.append(input);row.append(label);}const remove=element('button','Remove');remove.type='button';remove.className='secondary';remove.onclick=()=>row.remove();row.append(remove);$('fields').append(row);}
function editor(show){editing=show;$('settings').hidden=!show;$('monitor').hidden=show;document.body.className=show?'settings-view':data.view.size;if(!show){key='';render();}fit();}
$('edit').onclick=()=>{if(!connected)return;$('fields').replaceChildren();data.devices.forEach(field);$('size').value=data.view.size;$('columns').value=data.view.columns;editor(true);};
$('add').onclick=()=>field();$('cancel').onclick=()=>{editor(false);$('message').textContent='';};
$('settings').onsubmit=async e=>{e.preventDefault();$('save').disabled=true;try{const devices=[...$('fields').children].map(row=>({name:row.querySelector('[data-key=name]').value.trim(),ip:row.querySelector('[data-key=ip]').value.trim()}));await api('devices',devices);await api('view',{size:$('size').value,columns:Number($('columns').value)});data=await api('status');$('message').textContent='';editor(false);}catch(e){$('message').textContent=e.message;}finally{$('save').disabled=false;}};
$('check').onclick=async()=>{try{await api('check',{});}catch(e){$('message').textContent=e.message;}};poll();

let lastBounds='';new ResizeObserver(()=>{if(editing)return;const b=document.body.getBoundingClientRect();const bounds=Math.ceil(b.width)+','+Math.ceil(b.height);if(bounds!==lastBounds){lastBounds=bounds;fit();}}).observe(document.body);document.fonts.ready.then(fit);
