const $=s=>document.querySelector(s),editing=location.pathname==='/settings';let data,draft,layout='',fresh=false;const pending=new Map(),errors=new Map();
async function api(path,body){const r=await fetch('/api/'+path,{...(body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Projector-Monitor':'1'},body:JSON.stringify(body)}),signal:AbortSignal.timeout(5000)});const p=await r.json();if(!r.ok)throw Error(p.error||'Request failed');return p;}
const labels={online:'Connected',partial:'Partial',offline:'Offline',auth:'Login required',checking:'Checking',error:'Error',unknown:'Unknown'};
function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function button(text,fn,cls){const b=element('button',text,cls);b.type='button';b.onclick=fn;return b;}
function fit(){setTimeout(()=>api('fit',{view:editing?'settings':'monitor',viewportWidth:innerWidth,viewportHeight:innerHeight,contentHeight:Math.ceil(document.body.getBoundingClientRect().height)}).catch(()=>{}),600);}
function cards(){
 const key=JSON.stringify([data.view,data.projectors.map(p=>p.id)]);if(key!==layout){layout=key;document.body.className=data.view.size;document.documentElement.style.setProperty('--cols',Math.min(data.view.columns,data.projectors.length));$('#projectors').replaceChildren();for(const p of data.projectors){const card=element('article');card.dataset.id=p.id;const header=element('header');header.append(element('h2',p.config.name),element('span','','state'));card.append(header,element('div',p.config.ip,'address'));
 for(const [title,field,actions] of [['Power','power',[['On','power-on'],['Off','power-off']]],['Shutter','shutter',[['Open','shutter-open'],['Close','shutter-close']]]]){const row=element('div',undefined,'control-row'),value=element('div'),strong=element('strong','…');strong.dataset.field=field;value.append(element('span',title,'label'),strong);const group=element('div',undefined,'buttons');for(const [label,action]of actions){const b=button(label,()=>control(p.id,action),label==='Off'||label==='Close'?'secondary':'');b.dataset.action=action;b.disabled=true;group.append(b);}row.append(value,group);card.append(row);}
 const foot=element('div',undefined,'card-footer');foot.append(button('Readings',()=>readings(p.id),'secondary'),button('Check',()=>api('projectors/'+p.id+'/check',{}).catch(e=>{errors.set(p.id,e.message);render();}),'secondary'));card.append(foot,element('div','','notice'));$('#projectors').append(card);}fit();}
 render();
}
function render(){for(const p of data?.projectors||[]){const card=document.querySelector('article[data-id="'+p.id+'"]');if(!card)continue;const s=p.status||{},stale=!s.checkedAt||Date.now()-Date.parse(s.checkedAt)>25000,readable=fresh&&!stale&&['online','partial'].includes(s.connection);const status=!fresh?'offline':s.connection||'unknown';card.querySelector('h2').textContent=p.config.name;card.querySelector('.address').textContent=p.config.ip||'Not configured';const badge=card.querySelector('.state');badge.textContent=labels[status]||status;const stamp=s.checkedAt?new Date(s.checkedAt):null;if(stamp&&!isNaN(stamp)){const time=element('time',stamp.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}));time.dateTime=s.checkedAt;time.title='Last updated';badge.append(time);}badge.className='state '+status;
 if(pending.has(p.id)&&pending.get(p.id)===p.control?.id&&p.control.state!=='pending'){pending.delete(p.id);if(p.control.state==='failed')errors.set(p.id,p.control.message);}
 card.querySelectorAll('[data-action]').forEach(b=>b.disabled=!readable||pending.has(p.id)||p.control?.state==='pending');for(const field of ['power','shutter'])card.querySelector('[data-field="'+field+'"]').textContent=readable?s[field]||'Unknown':'…';card.querySelector('.notice').textContent=errors.get(p.id)||(!fresh?'Monitor unavailable':s.error||'');}
 $('#connection').textContent=fresh?'':'Disconnected';}
async function control(id,action){const p=data.projectors.find(p=>p.id===id);if(!p||pending.has(id)||!fresh)return;const requestId=Array.from(crypto.getRandomValues(new Uint8Array(16)),x=>x.toString(16).padStart(2,'0')).join('');pending.set(id,requestId);errors.delete(id);render();try{p.control=await api('projectors/'+id+'/control',{id:requestId,action,ip:p.config.ip,port:p.config.port});}catch(e){pending.delete(id);errors.set(id,e.name==='TimeoutError'?'No acknowledgement. Check status before retrying.':e.message);}render();}
function readings(id){const p=data.projectors.find(p=>p.id===id);$('#details-name').textContent=p.config.name;$('#readings').replaceChildren();for(const [field,title] of [['model','Model'],['input','Input'],['intakeC','Intake °C'],['exhaustC','Exhaust °C'],['projectorHours','Projector hours'],['lightHours','Light hours'],['freeze','Freeze'],['serial','Serial'],['firmware','Firmware'],['checkedAt','Updated']]){const row=element('div');row.append(element('dt',title),element('dd',String(p.status[field]??'Unknown')));$('#readings').append(row);}$('#details').showModal();}
function editors(){$('#editors').replaceChildren();draft.forEach((p,i)=>{const block=element('details',undefined,'editor');block.open=!p.ip;block.append(element('summary',p.name||'Projector '+(i+1)));const grid=element('div',undefined,'editor-grid');for(const [field,title,type]of [['name','Name','text'],['ip','IP address','text'],['port','Port','number'],['username','Username','text'],['password','Password','password']]){const label=element('label',title),input=element('input');input.type=type;input.value=field==='password'?'':p[field];input.autocomplete='off';input.setAttribute('aria-label',title+' '+(i+1));if(field==='password')input.placeholder=p.hasPassword?'Saved; blank keeps it':'Password';input.oninput=()=>{p[field]=field==='port'?Number(input.value):input.value;if(field==='name')block.querySelector('summary').textContent=input.value;};label.append(input);grid.append(label);}const remove=button('Remove projector',()=>{draft.splice(i,1);editors();},'secondary');remove.disabled=draft.length===1;grid.append(remove);block.append(grid);$('#editors').append(block);});$('#count').textContent=draft.length+' / 12';$('#add').disabled=draft.length===12;}
$('#add').onclick=()=>{if(draft.length<12){draft.push({id:'pj'+Date.now().toString(36),name:'Projector '+(draft.length+1),ip:'',port:1024,username:'dispadmin',password:''});editors();}};
$('#cancel').onclick=()=>location.assign('/');$('#close-details').onclick=()=>$('#details').close();
$('#settings').onsubmit=async e=>{e.preventDefault();$('#save').disabled=true;$('#error').textContent='';try{await api('layout',{size:$('#size').value,columns:Number($('#columns').value),projectors:draft});location.assign('/');}catch(e){$('#error').textContent=e.message;$('#save').disabled=false;}};
async function poll(){try{data=await api('status');fresh=true;if(editing){document.body.className='settings-view';$('#projectors').hidden=true;$('#footer').hidden=true;$('#settings').hidden=false;draft=data.projectors.map(p=>({...p.config,id:p.id,password:''}));$('#size').value=data.view.size;$('#columns').value=String(data.view.columns);editors();fit();return;}cards();}catch(e){fresh=false;if(editing)$('#error').textContent=e.message;else render();}if(!editing)setTimeout(poll,1000);}
poll();
