const $=id=>document.getElementById(id),editing=location.pathname==='/settings';let current,selected=[],pending=false,fresh=false,gridKey='',draft=null,portsKey='',fitKey='';
const element=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
async function api(path,body){const r=await fetch('/api/'+path,{signal:AbortSignal.timeout(8000),...(body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Videohub-Monitor':'1'},body:JSON.stringify(body)})});const result=await r.json();if(!r.ok)throw Error(result.error||'Request failed');return result;}
const ports=(key)=>current[key].filter(p=>current.settings[key]===null||current.settings[key].includes(p.number));
function routeBar(){const valid=selected.length>0&&fresh&&!pending&&!current.busy&&current.connection==='online'&&Date.now()-Date.parse(current.updatedAt)<15000&&selected.every(r=>current.locks[r.o]==='U'&&current.routes[r.o]===r.previous&&ports('inputs').some(p=>p.number===r.i)&&ports('outputs').some(p=>p.number===r.o));$('selection').textContent=selected.length?selected.map(r=>`${r.i} → ${r.o}`).join(', '):'Select crosspoints';$('take').disabled=!valid;$('take').textContent=pending?'Taking…':selected.length?`Take (${selected.length})`:'Take';$('cancel').disabled=!selected.length||pending;}

let fitTimer;
function fit(){clearTimeout(fitTimer);const measure=()=>{const table=document.querySelector('#matrix table');const base={compact:242,standard:292,large:342}[current?.settings.size]||242;const width=editing?740:Math.max(base,Math.ceil(table?.getBoundingClientRect().width||0)+14);const height=editing?Math.max(340,Math.min(720,document.body.getBoundingClientRect().height+2)):Math.max(180,Math.ceil(document.body.getBoundingClientRect().height)+2);return api('fit',{width:innerWidth,height:innerHeight,contentWidth:width,contentHeight:height}).catch(()=>{});};fitTimer=setTimeout(async()=>{await measure();setTimeout(measure,500);},350);}
window.addEventListener('resize',fit);
document.fonts.ready.then(fit);

function render(){document.body.className=current.settings.size;$('model').textContent=current.model||'Videohub Monitor';$('address').textContent=current.settings.host||'Set matrix IP in Settings';$('connection').textContent=fresh&&current.connection==='online'?'Connected':current.connection==='connecting'?'Connecting':'Offline';$('connection').className=fresh&&current.connection==='online'?'online':'offline';$('updated').textContent=current.updatedAt?new Date(current.updatedAt).toLocaleTimeString([],{hour12:false}):'';$('matrix').classList.toggle('stale',!fresh||current.connection!=='online');
 const inputs=ports('inputs'),outputs=ports('outputs'),flipped=current.settings.orientation==='inputs-top',rows=flipped?outputs:inputs,columns=flipped?inputs:outputs;const key=JSON.stringify([inputs,outputs,current.routes,current.locks,current.settings.size,flipped,selected,fresh,current.connection]);
 if(key!==gridKey){gridKey=key;const area=$('matrix'),scroll=[area.scrollLeft,area.scrollTop],table=element('table'),head=element('thead'),tr=element('tr');tr.append(element('th',flipped?'OUTPUTS ↓ / INPUTS →':'INPUTS ↓ / OUTPUTS →'));for(const o of columns){const th=element('th',undefined,!flipped&&current.locks[o.number]!=='U'?'locked':'');th.title=o.label+(!flipped&&current.locks[o.number]!=='U'?' (locked)':'');th.append(element('div',o.label,'output-label'),element('span',String(o.number),'number'));tr.append(th);}head.append(tr);table.append(head);const body=element('tbody');for(const rowPort of rows){const row=element('tr'),th=element('th',undefined,'rowhead');th.title=rowPort.label;th.append(element('span',String(rowPort.number),'number'),document.createTextNode(rowPort.label));row.append(th);for(const colPort of columns){const i=flipped?colPort:rowPort,o=flipped?rowPort:colPort;const td=element('td'),b=element('button');b.type='button';b.classList.toggle('active',current.routes[o.number]===i.number);b.classList.toggle('selected',selected.some(r=>r.i===i.number&&r.o===o.number));b.setAttribute('aria-label',`Input ${i.number} ${i.label} to output ${o.number} ${o.label}`);b.disabled=pending||!fresh||current.connection!=='online';b.onclick=()=>{const existing=selected.find(r=>r.o===o.number);selected=selected.filter(r=>r.o!==o.number);if(existing?.i!==i.number&&current.routes[o.number]!==i.number)selected.push({i:i.number,o:o.number,previous:current.routes[o.number],host:current.settings.host});$('error').textContent='';gridKey='';render();};td.append(b);row.append(td);}body.append(row);}table.append(body);area.replaceChildren(inputs.length&&outputs.length?table:element('p','Choose visible inputs and outputs in Settings.'));area.scrollLeft=scroll[0];area.scrollTop=scroll[1];}routeBar();const sizing=JSON.stringify([inputs.length,outputs.length,current.settings.size,flipped]);if(sizing!==fitKey){fitKey=sizing;fit();}}
function counts(){for(const key of ['inputs','outputs'])$(key==='inputs'?'input-count':'output-count').textContent=`${draft[key].size}/${current[key].length}`;}
function portLists(){for(const key of ['inputs','outputs']){const search=$(key==='inputs'?'input-search':'output-search').value.toLowerCase();$(key).replaceChildren();for(const p of current[key]){if(!`${p.number} ${p.label}`.toLowerCase().includes(search))continue;const label=element('label'),check=element('input');check.type='checkbox';check.checked=draft[key].has(p.number);check.onchange=()=>{check.checked?draft[key].add(p.number):draft[key].delete(p.number);counts();};label.append(check,document.createTextNode(`${p.number} ${p.label}`));$(key).append(label);}}counts();}
function settings(){if(!draft){$('host').value=current.settings.host;$('size').value=current.settings.size;$('orientation').value=current.settings.orientation||'inputs-left';draft={inputs:new Set(current.settings.inputs??current.inputs.map(p=>p.number)),outputs:new Set(current.settings.outputs??current.outputs.map(p=>p.number))};}
 const key=JSON.stringify([current.settings.host,current.inputs,current.outputs]);if(key!==portsKey){portsKey=key;for(const k of ['inputs','outputs'])if(current.settings[k]===null&&draft[k].size===0)current[k].forEach(p=>draft[k].add(p.number));portLists();}}
async function save(connectOnly=false){$('save').disabled=$('connect').disabled=true;try{await api('settings',{host:$('host').value.trim(),size:$('size').value,orientation:$('orientation').value,inputs:connectOnly?null:[...draft.inputs],outputs:connectOnly?null:[...draft.outputs]});if(connectOnly){draft=null;portsKey='',fitKey='';current=await api('state');settings();$('error').textContent='';}else location.assign('/');}catch(e){$('error').textContent=e.message;}finally{$('save').disabled=$('connect').disabled=false;}}
$('settings').onsubmit=e=>{e.preventDefault();save();};$('connect').onclick=()=>save(true);$('input-search').oninput=$('output-search').oninput=portLists;
document.querySelectorAll('[data-all]').forEach(b=>b.onclick=()=>{const key=b.dataset.all;draft[key]=new Set(current[key].map(p=>p.number));portLists();});document.querySelectorAll('[data-none]').forEach(b=>b.onclick=()=>{draft[b.dataset.none].clear();portLists();});
$('take').onclick=async()=>{if(!selected.length||pending||$('take').disabled)return;const chosen=selected.map(r=>({...r}));pending=true;gridKey='';render();try{const id=Array.from(crypto.getRandomValues(new Uint8Array(16)),n=>n.toString(16).padStart(2,'0')).join('');await api('route',{id,host:chosen[0].host,routes:chosen.map(r=>({input:r.i,output:r.o,previous:r.previous}))});$('error').textContent='';selected=[];}catch(e){$('error').textContent=e.name==='TimeoutError'?'No acknowledgement. Check the matrix before retrying.':e.message;selected=[];}finally{pending=false;gridKey='';render();}};
$('cancel').onclick=()=>{selected=[];gridKey='';render();};
async function poll(){try{const next=await api('state');if(current&&next.settings.host!==current.settings.host)selected=[];current=next;fresh=true;if(editing){settings();if(!fitKey){fitKey='settings';fit();}}else render();}catch(e){fresh=false;if(!editing&&current)render();$('error').textContent='Monitor unavailable';}setTimeout(poll,1000);}
$('monitor').hidden=editing;$('settings').hidden=!editing;poll();
