const $=s=>document.querySelector(s);let config,available=[],clocks=[];
const editing=location.pathname==='/settings';
async function json(url,options){const r=await fetch(url,options);const p=await r.json();if(!r.ok)throw Error(p.error||'Request failed');return p;}
function label(zone){return zone==='UTC'?'UTC':zone.split('/').slice(1).join(' / ').replaceAll('_',' ');}
function zoneRows(){const root=$('#zones');root.replaceChildren();config.zones.forEach((zone,i)=>{const row=document.createElement('div');row.className='zone-row';const select=document.createElement('select');select.setAttribute('aria-label','Timezone '+(i+1));for(const z of available){const o=document.createElement('option');o.value=z;o.textContent=z.replaceAll('_',' ');o.selected=z===zone;select.append(o);}select.onchange=()=>{config.zones[i]=select.value;};const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.setAttribute('aria-label','Remove timezone '+(i+1));remove.disabled=config.zones.length===1;remove.onclick=()=>{config.zones.splice(i,1);zoneRows();};row.append(select,remove);root.append(row);});$('#add').disabled=config.zones.length>=8;$('#count').textContent=config.zones.length+' / 8';}
function tick(){const now=new Date();for(const c of clocks){c.time.textContent=c.tf.format(now);c.time.dateTime=now.toISOString();c.date.textContent=c.df.format(now);c.time.title=c.zf.formatToParts(now).find(p=>p.type==='timeZoneName').value;}setTimeout(tick,1000-Date.now()%1000);}
async function init(){try{config=await json('/api/settings');if(editing){document.body.className='settings-view';$('#clocks').hidden=true;$('#footer').hidden=true;$('#settings').hidden=false;available=(await json('/timezones.json')).filter(z=>{try{new Intl.DateTimeFormat('en',{timeZone:z});return true;}catch{return false;}});$('#size').value=config.size;zoneRows();}else{document.body.className=config.size;for(const zone of config.zones){const el=document.createElement('section'),h=document.createElement('h2'),time=document.createElement('time'),date=document.createElement('div');h.textContent=label(zone);h.title=zone;date.className='date';el.append(h,time,date);$('#clocks').append(el);clocks.push({time,date,tf:new Intl.DateTimeFormat('en-GB',{timeZone:zone,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}),df:new Intl.DateTimeFormat('en-GB',{timeZone:zone,weekday:'short',day:'2-digit',month:'short'}),zf:new Intl.DateTimeFormat('en-GB',{timeZone:zone,timeZoneName:'short'})});}tick();}}catch(e){$('#error').textContent=e.message;}}
$('#add').onclick=()=>{if(config.zones.length<8){config.zones.push(available.find(z=>!config.zones.includes(z))||'UTC');zoneRows();}};
$('#cancel').onclick=()=>location.assign('/');
$('#settings').onsubmit=async e=>{e.preventDefault();$('#save').disabled=true;$('#error').textContent='';try{await json('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({size:$('#size').value,zones:config.zones})});location.assign('/');}catch(e){$('#error').textContent=e.message;$('#save').disabled=false;}};
init().then(()=>fetch('/api/fit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({view:editing?'settings':'clock'})}).catch(()=>{}));
